yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path(
         '', 
         views.index, 
         name='index'
         ),
    path(
         'group/<slug:slug>/', 
         views.group_posts, 
         name='group_list'
         )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
               path('admin/', admin.site.urls),
               path('', include('posts.urls', namespace='posts'))
              ]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """Таблица, содержащая группы пользователей."""
    title = models.TextField()
    slug = models.SlugField(
                            unique=True, 
                            max_length=100, 
                            default='title'
                            )
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    """Таблица, содержащая сообщения (посты) пользователей."""
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
                               User,
                               on_delete=models.CASCADE,
                               related_name='posts_all'
                               )
    group = models.ForeignKey(
                              Group,
                              blank=True,
                              null=True,
                              on_delete=models.CASCADE
                              )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


""" Одна строка вместо тысячи слов на SQL:
переменную posts будет сохранена выборка из 10 объектов модели Post,
отсортированных по полю pub_date по убыванию (от больших значений к меньшим)."""
def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    template = 'posts/index.html'
    """В словаре context отправляем информацию в шаблон."""
    context = {
        'posts': posts,
        'title_index':'Последние обновления на сайте'
    }
    return render(request, template, context) 

def group_posts(request, slug):
    """Cтраница  публикаций."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    """Метод .filter позволяет ограничить поиск по критериям.
    Это аналог добавления
    условия WHERE group_id = {group_id}."""
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    """posts = group.posts_all.all()[:10]."""
    context = {
               'group': group,
               'posts': posts,
               'title_groups':'Записи сообщества -'
              }
    return render(request, template, context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    {% include 'posts/head_block.html' %}
    {% block title %}
    {% endblock title %}
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        {% block content %}
        {% endblock content %}
        <!-- под последним постом нет линии -->
      </div>
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <span style="color:red">Ya</span>tube</a>
    </a>
  </div>
</nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  <title>{{ title_groups }}</title>
{% endblock title %}
{% block content %}
  <h1>{{ title_groups }} {{ group.title }}</h1>
   {% for post1 in posts %}
    <ul>
      <li>
        Автор: {{ post1.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post1.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post1.text }}</p> 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock content %}

yatube/templates/posts/head_block.html
{% load static %}
<meta charset="utf-8"> <!-- Кодировка сайта -->
<!-- Сайт готов работать с мобильными устройствами -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Загружаем фав-иконки -->
<link rel="icon" href= "{% static 'img/fav/fav.ico' %}" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<!-- Подключен файл со стандартными стилями бустрап -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  <title>{{ title_index }}</title>
{% endblock title %}
{% block content %}
  <h1>{{ title_index }}</h1>
  {% for post1 in posts %}
    <ul>
      <li>
        Автор: {{ post1.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post1.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post1.text }}</p>
    {% if post1.group %}
      <a href="{% url 'posts:group_list' post1.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock content %}

yatube/templates/posts/index1.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Другие мета-теги тут -->
    <!-- Подключили адаптивность  -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Подключили CSS-файл Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous">
    <!-- После стилевого файла Bootstrap можно
         написать собственные стили в теге <style> -->
    <!-- А лучше подключить свой CSS-файл и описать свои стили в нём:
        <link rel="stylesheet" href="css/style.css"> -->
    <style>
      .card {
        background: #eee;
        box-shadow: rgb(0 0 0 / 50%) 10px 10px 5px;
      }
    </style>
  </head>
  <body>

    <!-- Классы Bootstrap можно применять и к семантическим блокам. -->
    <div class="container">

      <!-- Начало глобального div.row с двумя колонками: 
       в левой колонке - имена авторов, в правой - блоки с текстом -->
      <div class="row">

        <!-- Начало левой колонки сайта со списком авторов -->
        <aside class="col-12 col-md-3">
          <ul class="list-group">
            <li class="list-group-item">Аксентий Поприщин</li>
            <li class="list-group-item">Робинзон Крузо</li>
            <li class="list-group-item">Чарли Гордон</li>
            <li class="list-group-item">Владимир Высоцкий</li>
          </ul>
        </aside>
        <!-- Конец левой колонки сайта -->

        <!-- Начало правой (широкой) колонки сайта -->
        <section class="col-12 col-md-9">

          <!-- Можно разбить на колонки содержимое любого блока.
           В этом div.row созданы четыре колонки с анонсами постов -->
          <div class="row">

            <!-- Начало первой колонки -->
            <article class="col-12 col-md-6 col-xl-6">
              <div class="card">
                <h5 class="card-header">Аксентий Поприщин</h5>
                <div class="card-body">
                  <h6 class="card-subtitle">Число 25</h6>
                  <p>
                    Сегодня великий инквизитор пришел в мою комнату, но я,
                    услышавши еще издали шаги его, спрятался под стул.
                  </p>
                  <a href="" class="btn btn-primary">Читать целиком</a>
                </div>
              </div>
            </article>
            <!-- Конец первой колонки -->

            <!-- Начало второй колонки -->
            <article class="col-12 col-md-6 col-xl-6">
              <div class="card">
                <h5 class="card-header">Робинзон Крузо</h5>
                <div class="card-body">
                  <h6 class="card-subtitle">25 октября 1659 года</h6>
                  <p>
                    Шквальный ветер сотрясал остров целую ночь,
                    а наутро я увидел, что наш корабль разнесло в щепки.
                  </p>
                  <a href="" class="btn btn-primary">Читать целиком</a>
                </div>
              </div>
            </article>
            <!-- Конец второй колонки -->

            <!-- Начало третьей колонки -->
            <article class=" col-12 col-md-6 col-xl-6">
              <div class="card">
                <h5 class=" card-header">Чарли Гордон</h5>
                <div class="card-body">
                  <h6 class="card-subtitle">1 атчет 3 марта</h6>
                  <p>
                    Док Штраус сказал што я должен писать все што я думаю и
                    помню и все што случаеца со мной с севодня. Я не знаю
                    пачему но он гаварит што это важно штобы они могли
                    увидить што я падхажу им.
                  </p>
                  <a href="" class="btn btn-primary">Читать целиком</a>
                </div>
              </div>
            </article>
            <!-- Конец третьей колонки -->

            <!-- Начало четвёртой колонки -->
            <article class=" col-12 col-md-6 col-xl-6">
              <div class="card">
                <h5 class=" card-header">Владимир Высоцкий</h5>
                <div class="card-body">
                  <h6 class="card-subtitle">3 апреля 1976 года</h6>
                  <p>
                    Если б Кащенко, к примеру, лёг лечиться к Пирогову -
                    Пирогов бы без причины резать Кащенку не стал…
                  </p>
                  <a href="" class="btn btn-primary">Читать целиком</a>
                </div>
              </div>
            </article>
            <!-- Конец четвёртой колонки -->
          </div>  <!-- Конец вложенного div.row -->

        </section>  <!-- Конец правой (широкой) колонки сайта -->
      </div>  <!-- Конец div.row  -->
    </div>  <!-- Конец div.container -->
  </body>
</html>

yatube/templates/posts/index2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
	<head>
		<title> Cтальной интеллект</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	</head>
	<LINK rel="stylesheet" type="text/css" href="styling_sheet.css">
	<body>
<div id="whole_document">	
<div id="header">
	<h1>Промсталькомплект</h1> 
	<h1>+7-905-328-41-70</h1>
</div>
<div id="right_header">
<img src="images/1_1_2_land_design.jpg" height=90 width=150> </img>
</div>	
<div id="middle_header">
<img src="images/1_3_7_socle_and_blind_area.jpg" height=90 width=150> </img>
</div>	
<div id="menu" >
	<ol><span class="title"><a href="index.html"> Главная</a></span>
		<li><ol start=11> <span class="title"><a href="index.html">Строительство зданий и сооружений</a> </span>
			<li><div id="menu1" class="menue">
					<span class="title"><a href="page2_project.html">Проектирование </a> </span>
							<ol start=111>	<li><a href="page2_project.html">Предпроектное обследование земельного участка и инженерных коммуникаций</a></li>  
											<li><a href="page3_dust.html" >Создание макета объекта, ландшафтного дизайна</a></li>   
											<li><a href="page3_dust.html">Согласование проекта и получение разрешительных документов</a></li>   
											<li><a href="page3_dust.html">Составление сметы</a></li>
							</ol>
					</div></li> 
				 
			<li><a href="page4_storage.html">Организация временного складирования строительных материалов</a>  
					<ol start=121><li><a href="page4_storage.html">Подведение электроэнергии</a></li>  
                                  <li><a href="page4_storage.html">Установка временного бытового помещения</a></li>  
                                  <li><a href="page4_storage.html">Создание нормативных санитарно-бытовых условий работающим на стройплощадке</a></li>  
                                  <li><a href="page4_storage.html">Организация круглосуточной охраны строительной площадки</a></li>
					</ol></li>  
            	
			<li><a href="page5_foundation.html">Закладка фундамента.</a>  
                   <ol start=131>  <li><a href="page5_foundation.html">Земляные работы</a></li>  
                                   <li><a href="page5_foundation.html">Подведение систем водоснабжения и водоотведения</a></li>  
                                   <li><a href="page5_foundation.html">Подсыпка песчаной подушки</a></li>  
                                   <li><a href="page5_foundation.html">Гидроизоляция фундамента</a></li>  
                                   <li><a href="page6_concrete.html">Армирование фундамента</a></li>  
                                   <li><a href="page6_concrete.html">Бетонирование фундамента</a></li>  
									<li><a href="page6_concrete.html">Цоколь и отмостка</a></li>
					</ol></li>  
            <li><a href="page7_walls.html">Возведение стен и перекрытий, устройство крыши</a>  
                    <ol start=141> <li><a href="page7_walls.html">Монтаж подъемных механизмов</a></li>  
                                   <li><a href="page7_walls.html">Армирование и бетонирование стен</a></li>  
                                   <li><a href="page8_stires.html">Монтаж перекрытий и лестничных маршей</a></li>  
                                   <li><a href="page8_stires.html">Монтаж дымоходов, шахт для инженерных коммуникаций и вентиляции</a></li>  
                                   <li><a href="page9_roof.html">Устройство крыши</a></li>  
                                   <li><a href="page9_roof.html">Облицовка наружных стен</a></li>
					</ol></li>  
            <li><a href="page10_tubes.html">Монтаж инженерных систем</a>
                    <ol start=1501><li><a href="page11_tube2.html">Система водоснабжения и водоотведения</a></li>  
                                   <li><a href="page12_cabel.html">Система электропитания</a></li>  
                                   <li><a href="page13_cab2.html">Структурированная кабельная сеть</a></li>
                                   <li><a href="page14_climate.html">Вентиляция</a></li>  
                                   <li><a href="page15_clim2.html">Система климат контроля</a></li>  
                                   <li><a href="page16_gas.html">Система газоснабжения</a></li>  
                                   <li><a href="page17_smart.html">Охранно-пожарная сигнализация и приводы системы «Умный дом»</a></li>  
                                   <li><a href="page18_controller.html">Контроллер</a></li>
                                   <li><a href="page19_sensor.html">Датчики</a></li>
                                   <li><a href="page20_video.html">Видеонаблюдение</a></li>  
                                   <li><a href="page20_video.html">Установка солнечных панелей в качестве резервного источника электроснабжения</a></li>
					</ol></li>  
            <li><a href="page21_inside.html">Отделка внутренних помещений</a>  
                    <ol start=161> <li><a href="page21_inside.html">Выравнивание стен и полов</a></li>  
                                   <li><a href="page21_inside.html">Укладка керамической плитки, паркета</a></li>  
                                   <li><a href="page22_door.html">Установка дверей и окон</a></li>  
                                   <li><a href="page23_fireplace.html">Установка камина</a></li>
                    </ol></li>
			</ol></li>
		<li><a href="page24_outside.html">Обустройство придомового участка</a>  
			<ol start=21>	<li><a href="page24_outside.html">Возведение забора</a> 
							<ol start=211><li><a href="page24_outside.html">Монтаж столбов и перекладин</a></li>  
                                     <li><a href="page24_outside.html">Установка ворот</a></li>
							</ol></li>  
							<li><a href="page25_sauna.html">Строительство бани</a>  
								<ol start=221>	<li><a href="page25_sauna.html">Земляные работы и фундамент</a></li>  
												<li><a href="page25_sauna.html">Подведение систем водоснабжения и водоотведения</a></li>  
												<li><a href="page25_sauna.html">Установка котла отопления и подогрева воды</a></li>  
												<li><a href="page25_sauna.html">Возведение стен, устройство крыши</a></li>
                                </ol></li>  
							<li><a href="page26_garage.html">Строительство гаража</a></li>  
							<li><a href="page26_garage.html">Строительство «летней» кухни, ротонды, погреба, пагоды, беседки в стиле Дзен</a></li>  
							<li><a href="page26_garage.html">Строительство фонтанов и бассейнов</a></li>  
							<li><a href="page26_garage.html">Бетонирование дорожек и подъездов</a></li>  
							<li><a href="page26_garage.html">Обустройство лужаек и газонов</a></li>
            </ol></li>  
	<li> <a href="page27_access.html">Монтаж системы контроля доступа</a>  
            <ol start=31>	<li> <a href="page27_access.html">Установка охранных датчиков по периметру участка</a></li>  
							<li> <a href="page27_access.html">Установка устройств сканирующих облик человека, номер автомобиля</a></li>  
							<li> <a href="page28_computer.html">Настройка компьютера управления и пусконаладочные работы</a></li>
            </ol></li>  
<li><a href="page29_safepolis.html">Создание подсистем АПК «Безопасный город»</a></li>   
	<ol start=41><li> <a href="page29_safepolis.html">Программное обеспечение</a></li>   
		<li><a href="page30_village.html">«Умный дом»</a></li>   
		<li><a href="page30_village.html">«Умный район»</a> </li>   
		<li><a href="page31_communication.html"> Системы связи и оповещения</a></li>   
		<li><a href="page31_communication.html"> Системы контроля и управления доступом</a></li>
	</ol>  
<li><a href="page32_cloud.html">Удаленное хранилище</a></li>  
<li><a href="page33_support.html"> Поддержка</a></li>  
<li><a href="page34_plans.html"> Планы и проекты</a></li> 
<li><a href="page35_manuals.html">Справочная информация</a></li>  
<li><a href="page36_contacts.html">Контактная информация</a></li>
</ol> 
</div>
<div id="main_page">
<h2>Промсталькомплект - стальной интеллект</h2> 
<p>Общество с ограниченной ответственностью «Промсталькомплект» (далее - ПСК) более 
15 лет предоставляет населению, предпринимательскому сообществу, бюджетным организациям
широкий спектр услуг, включающий в себя проектирование, строительство, установку 
компьютерного и телекоммуникационного оборудования, создание информационных систем. 
Основными характеристиками созданных ПСК объектов заслуженно считается качество 
произведенных работ, надежность построенных сооружений, доступность 
предлагаемых товаров и услуг в границах умеренного ценового диапазона.</p> 
<ul>ПСК – это: 
<li>Строительство зданий и сооружений </li> 
<li>Система «Умный дом» </li> 
<li>Сегменты АПК «Безопасный город» </li> 
<li>Программное обеспечение </li> 
<li>Системы связи и оповещения </li> 
<li>Системы контроля и управления доступом </li></ul> 
<h2>1. Строительство зданий и сооружений </h2> 
<p>ПСК осуществляет строительство «под ключ» домов и коттеджей малой этажности.
 Полный цикл работ включает в себя шесть основных этапов: </p> 
<ul><li>проектирование, </li> 
<li>закупка строительных материалов и складирование, </li> 
<li>земляные работы и закладка фундамента, </li> 
<li>возведение стен и устройство крыши, </li> 
<li>монтаж инженерных систем, </li> 
<li>отделка внутренних помещений и фасада. </li></ul> 
<p>Технология возведения зданий, применяемая ПСК, включает в себя элементы
монолитного и блочного строительства в соотношении 3:7. Подобное сочетание
позволяет получить в итоге сооружение любой этажности, стены которого состоят 
из армированного бетона внутри и строительных блоков — снаружи. 
Прочность каркаса,  произвольный вид стен и перекрытий — эти основные преимущества
монолитного типа постройки обеспечивают оригинальность, надежность и долговечность 
конструкций, созданных ПСК.</p> 
<p>Стоимость строительства определяется на этапе проектирования. </p> 
</div>
<div id="logo1">
<img src="images/0_1_background_try_six.jpg" height=1705 width=700> </img>
</div>	
<div id="logo">
<img src="images/prom_logo_31.jpg" height=50 width=50> </img>
</div>	
<div id="lift3">
<img src="images/lift3.png" height=150 width=90> </img>
</div>	
</div>
<script>
    var menuElem = document.getElementById('.menu1');
    var titleElem = menuElem.querySelector('.title');

    titleElem.onclick = function() {
    menuElem.classList.toggle('open');
    };
</script>
</body>
</html>
 

yatube/templates/posts/index3.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Дама сдавала багаж | С.Маршак</title>
  <style>
    body {
      background: rgb(0, 255, 76);
    }
    footer, #top-nav {
      background: rgb(139, 10, 118);
    }
    .nav-item {
      display: inline-block;
      font-size: 40px;
      font-family: sans-serif;
    }
    .active a {
      color: white;
    }
    .negative {
      color: rgb(228, 212, 212);
      background: rgb(17, 3, 97);
    }
    #footer-inner {
      font-size: 30px;
    }
  </style>
</head>
<body>
  <header>
    <nav id="top-nav">
      <ul>
        <li class="nav-item active">
          <a href="/">Главная страница</a>
        </li>
        <li class="nav-item">
          <a href="about/">О сайте</a>
        </li>
      </ul>
    </nav>
  </header>
  <main>
    <p class="negative">
      Дама сдавала багаж:
    </p>
    <ul>
      <li>Диван,</li>
      <li>Чемодан,</li>
      <li>Саквояж...</li>
    </ul>
  </main>
  <footer>
    <div id="footer-inner">
      Текст в подвале
    </div>
  </footer>
</body>

yatube/templates/posts/index6.html
<!DOCTYPE html> 
<html lang="ru">
  <head>
  </head>
  <body>
    <h1>Главная страница</h1>
  </body>
</html> 
<!-- templates/posts/index.html -->

yatube/templates/posts/post_L_Tolstoy_28071854.html
<ul>
  <li>
    Автор: Лев Толстой
  </li>
  <li>
    Дата публикации: 30 июля 1854
  </li>
</ul>
<p>
  [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
  Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо.
  Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться
  къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде
  и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
  ебѣ за нынѣшній день. (3)
</p>

yatube/templates/posts/post_L_Tolstoy_29071854.html
<ul>
  <li>
    Автор: Лев Толстой
  </li>
  <li>
    Дата публикации: 29 июля 1854
  </li>
</ul> 
<p>
  Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки
  съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ,
  что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень
  веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня;
  отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками.
  — Тогда бы я всегда былъ веселъ и почти всегда счастливъ.
  Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ,
  чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ
  накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за
  безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
</p>

yatube/templates/posts/post_L_Tolstoy_30071854.html
<ul>
  <li>
    Автор: Лев Толстой
  </li>
  <li>
    Дата публикации: 30 июля 1854
  </li>
</ul>
<p>
  [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
  Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо.
  Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться
  къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде
  и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
  ебѣ за нынѣшній день. (3)
</p>